twitter:
    consumer_key: opfHIzsLnDX5BVNhaJV9GIavK
    consumer_secret: MyHyl52InMtSVHlH7EyH7vSddC0TGWdHDvoz9yThBWKkyPSXEd
    access_token: 14517528-cZhEvYNq7cgwDv9KTJNiDrMO5xxezmtnSGrmLmeF3
    access_token_secret: AXkAuIx2IaF5k87xm9LOcmh0MR3t4GUkpv7Q6Zfl7HfXy
instagram:
    client_id: b2ad1e4397e74a01bebe074f03d59a55
    client_secret: cf9f078c478848bcaaaea4d802073d2e
    access_token: 1604585272.1fb234f.e6f995c699074de99c68f56043ff184d