"""empty message

Revision ID: 899d1f4ea87
Revises: None
Create Date: 2015-05-25 16:31:31.372829

"""

# revision identifiers, used by Alembic.
revision = '899d1f4ea87'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
